# Generated by Django 4.2.10 on 2024-03-06 04:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date time at which an object was created', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date time at which an object was modified', verbose_name='updated at')),
                ('name', models.CharField(max_length=20, verbose_name='name')),
                ('slug', models.SlugField(blank=True, max_length=20, null=True, unique=True, verbose_name='slug')),
                ('image', models.FileField(blank=True, null=True, upload_to='icons/', verbose_name='image')),
            ],
            options={
                'db_table': 'tag_info',
                'ordering': ['-created_at'],
                'get_latest_by': 'created_at',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date time at which an object was created', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date time at which an object was modified', verbose_name='updated at')),
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=100, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('body', models.TextField(max_length=500)),
                ('image', models.URLField(blank=True, max_length=500, null=True, verbose_name='url_image')),
                ('is_draft', models.BooleanField(default=False, verbose_name='is_draft')),
                ('publish_date', models.DateTimeField(blank=True, null=True, verbose_name='published_date')),
                ('url', models.SlugField(blank=True, max_length=255, null=True, verbose_name='url')),
                ('link', models.URLField(max_length=500, verbose_name='link')),
                ('artist', models.CharField(max_length=500, verbose_name='artist')),
                ('tags', models.ManyToManyField(to='a_posts.tag', verbose_name='tags for the post')),
            ],
            options={
                'db_table': 'post_info',
                'ordering': ['-created_at'],
                'get_latest_by': 'created_at',
                'abstract': False,
            },
        ),
    ]
