# Generated by Django 4.2.10 on 2024-03-26 17:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('a_posts', '0007_likedcomment_comment_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikedRepliesComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date time at which an object was created', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date time at which an object was modified', verbose_name='updated at')),
                ('reply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_reply_comments', to='a_posts.reply', verbose_name='liked reply comments')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_liked_reply_comment', to=settings.AUTH_USER_MODEL, verbose_name='user who liked the reply comment')),
            ],
            options={
                'db_table': 'liked_reply_comment_info',
                'ordering': ['-created_at'],
                'get_latest_by': 'created_at',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='reply',
            name='likes',
            field=models.ManyToManyField(related_name='liked_reply_comments', through='a_posts.LikedRepliesComment', to=settings.AUTH_USER_MODEL),
        ),
    ]
